language: cpp


matrix:
  include:
    - os: linux
      cache: bundler
      sudo: required
      dist: bionic
      addons:
        apt:
          packages:
            - libboost-all-dev
            - ninja
    - os: osx
      cache: bundler
      addons:
        homebrew:
          packages:
          - libressl
          - boost
          - ninja

compiler:
  - gcc
  - clang

before_install:
  - if [ "$TRAVIS_OS_NAME" != "osx" ]; then git clone https://github.com/libressl-portable/portable && cd portable && ./autogen.sh && ./configure && make -j4 && sudo make install ; fi

script:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then ./build_osx_brew.sh -GNinja ; else ./setup_build.sh -GNinja ; fi
  - cd build
  - ninja && ninja test