language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
      cache:
        apt: true
        ccache: true
      dist: bionic
      env:
         - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
         - LIBRESSL_ROOT_DIR="/usr/local/opt/libressl"
         - LD_LIBRARY_PATH=/usr/local/opt/libressl:$LD_LIBRARY_PATH
         - CMAKE_PLATFORM_ARGS="-DFETCH_LIBRESSL=True"
      addons:
        apt:
          packages:
            - libboost-log-dev
            - libboost-locale-dev
            - libssl-dev
            - ninja-build
    - os: linux
      compiler: clang
      cache:
        apt: true
        ccache: true
      dist: bionic
      env:
         - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
         - LIBRESSL_ROOT_DIR="/usr/local/opt/libressl
         - LD_LIBRARY_PATH=/usr/local/opt/libressl:$LD_LIBRARY_PATH
         - CMAKE_PLATFORM_ARGS="-DFETCH_LIBRESSL=True"
      addons:
        apt:
          packages:
            - clang-5.0
            - libboost-log-dev
            - libboost-locale-dev
            - libssl-dev
            - ninja-build
    - os: osx
      compiler: cmake
      cache:
        ccache: true
        directories:
          - $HOME/Library/Caches/Homebrew
      osx_image: xcode11.3
      env:
         - MATRIX_EVAL=""
         - LIBRESSL_ROOT_DIR="/usr/local/opt/libressl"
         - PATH="/usr/local/opt/ccache/libexec:$PATH"
         - CMAKE_PLATFORM_ARGS="-DBoost_NO_BOOST_CMAKE=ON"
      addons:
        homebrew:
          packages:
          - libressl
          - boost
          - ninja
          - ccache

before_cache:
  - brew cleanup

git:
  submodules: false

before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
  - eval "${MATRIX_EVAL}"
  - test -n $CC  && unset CC
  - test -n $CXX && unset CXX

script:
  - git submodule update --remote --recursive --init
  - mkdir -p ./build
  - cd build
  - cmake -GNinja ${CMAKE_PLATFORM_ARGS} ..
  - ninja && ninja test