language: cpp


matrix:
  include:
    - os: linux
      compiler: gcc
      cache: bundler
      dist: bionic
      env:
         - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - libboost-all-dev
            - ninja-build
    - os: linux
      compiler: clang
      cache: bundler
      dist: bionic
      env:
         - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
      addons:
        apt:
          sources:
            - llvm-toolchain-bionic-5.0
          packages:
            - clang-5.0
            - libboost-all-dev
            - ninja-build
    - os: osx
      compiler: g++
      cache: bundler
      osx_image: xcode11.3
      env:
         - MATRIX_EVAL=""
      addons:
        homebrew:
          packages:
          - libressl
          - boost
          - ninja


before_install:
  - eval "${MATRIX_EVAL}"
  - if [ "$TRAVIS_OS_NAME" != "osx" ]; then git clone https://github.com/libressl-portable/portable && cd portable && ./autogen.sh && ./configure && make -j4 && sudo make install ; fi

script:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then LIBRESSL_ROOT_DIR=/usr/local/opt/libressl ; fi
  - git submodule update --remote --recursive --init
  - mkdir -p ./build
  - cd build
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then cmake -GNinja -DBoost_NO_BOOST_CMAKE=ON  ..; else cmake -GNinja ..; fi
  - ninja && ninja test