language: cpp


matrix:
  include:
    - os: linux
      compiler: gcc
      cache:
        apt: true
        ccache: true
      dist: bionic
      env:
         - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
         - LIBRESSL_ROOT_DIR="/usr/local/opt/libressl"
         - LD_LIBRARY_PATH=/usr/local/opt/libressl:$LD_LIBRARY_PATH
      addons:
        apt:
          packages:
            - libboost-log-dev
            - libboost-locale-dev
            - libssl-dev
            - ninja-build
    - os: linux
      compiler: clang
      cache:
        apt: true
        ccache: true
      dist: bionic
      env:
         - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
         - LIBRESSL_ROOT_DIR="/usr/local/opt/libressl
         - LD_LIBRARY_PATH=/usr/local/opt/libressl:$LD_LIBRARY_PATH
      addons:
        apt:
          packages:
            - clang-5.0
            - libboost-log-dev
            - libboost-locale-dev
            - libssl-dev
            - ninja-build
    - os: osx
      compiler: cmake
      cache:
        ccache: true
      osx_image: xcode11.3
      env:
         - MATRIX_EVAL=""
         - LIBRESSL_ROOT_DIR="/usr/local/opt/libressl"
         - PATH="/usr/local/opt/ccache/libexec:$PATH"
      addons:
        homebrew:
          packages:
          - libressl
          - boost
          - ninja
          - ccache


before_install:
  - eval "${MATRIX_EVAL}"
  - test -n $CC  && unset CC
  - test -n $CXX && unset CXX
install:
  - if [ "$TRAVIS_OS_NAME" != "osx" ]; then mkdir -p /tmp/libressl/build && curl -L https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-3.0.2.tar.gz | tar --strip-components=1 zx -C /tmp/libressl && pushd /tmp/libressl/build && cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr/local/opt/libressl -GNinja .. && ninja && sudo ninja install && popd ; fi
script:
  - git submodule update --remote --recursive --init
  - mkdir -p ./build
  - cd build
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then cmake -GNinja -DBoost_NO_BOOST_CMAKE=ON  ..; else cmake -GNinja ..; fi
  - ninja && ninja test