language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - libboost-all-dev
before_install:
  - if [ "$TRAVIS_OS_NAME" != "osx" ]; then git clone https://github.com/libressl-portable/portable && cd portable && ./autogen.sh && ./configure --prefix=/usr/local/libressl --with-openssldir=/usr/local/libressl && make && make install ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update          ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install libressl; fi

script:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then ./build_osx_brew.sh ; else ./setup_build.sh ; fi
  - cd build
  - make && make test